export let stateList = {
    // '*** United States ***',
    'United States': [
        'Alaska',
        'Alabama',
        'Arkansas',
        'Arizona',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Florida',
        'Georgia',
        'Hawaii',
        'Iowa',
        'Idaho',
        'Ilinonis',
        'Indiana',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Massachussetts',
        'Maryland',
        'Maine',
        'Michigan',
        'Minnesota',
        'Missouri',
        'Mississippi',
        'Montana',
        'North Carolina',
        'North Dakota',
        'Nebraska',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'Nevada',
        'New York',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennslyvania',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Virginia',
        'Vermont',
        'Washington',
        'Wisconsin',
        'West Virginia',
        'Wyoming'
    ],
    // '*** CANADA ****',
    'Canada': [
        'Alberta',
        'Britsih Columbia',
        'Manitoba',
        'New Brunswick',
        'NewFoundland and Labrador',
        'Nova Scotia',
        'Northwest Territories',
        'Nunavut',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan',
        'Yukon',
    ]
    ,
    // '*** MEXICO ***',
    'Mexico': [
        'Auascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Coahuila',
        'Colima',
        'Distrito Federal',
        'Durango',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Mexico',
        'Michoacan',
        'Morelos',
        'Nayarit',
        'Nuevo Leon',
        'Oaxaca',
        'Puebla',
        'Queretaro',
        'Quintana Roo',
        'San Luis Potosi',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tiaxcala',
        'Veracruz',
        'Yucatan',
        'Zacatecas',
    ]
}

export let countryList = [
    'Argentina',
    'Australia',
    'Austria',
    'Bangladesh',
    'Belarus',
    'Belgium',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Cambodia',
    'Canada',
    'Chile',
    'China',
    'Columbia',
    'Costa Rica',
    'Croatia',
    'Czech Republic',
    'Denmark',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Estonia',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Greece',
    'Guatemala',
    'Honduras',
    'HongKong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Ireland',
    'Israel',
    'Italy',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Korea',
    'Kuwait',
    'Latvia',
    'Lebanon',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Malysia',
    'Mexico',
    'Netherlands',
    'New Zealand',
    'Norway',
    'Pakistan',
    'Panama',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Saudai Arabia',
    'Serbia',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'Spain',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanezuela',
    'Viet Nam',
]


export let statusList = [
    "Draft",
    "Pending",
    "Issued",
    "Disputed",
    "Cancelled",
    "Closed",
    "Final"
]

export let adminStatusList = [
    "Draft",
    "Cancelled",
    "Closed",
    "Final"
]

export let adminStatusIssuedList = [
    "Draft",
    "Issued",
    "Cancelled",
    "Closed",
    "Final"
]

export let supplierStatusList = [
    "Issued",
    "Disputed",
    "Cancelled",
    "Closed",
    "Final"
]

export let primaryNonConformityList = [
    "Customer Impact",
    "Customer Containment",
    "Unauthorized Change",
    "Program Management",
    "SQD Escalation",
    "Preventive In Field Action",
    "Cost Recovery"
]

export let secondaryNonConformityList = {
    'Customer Impact': ['Minor', 'Major'],
    'Customer Containment': ['Yardhold with Supplier Alert', 'Yardhold without Supplier Alert', '3CPR/Controlled Shipping Level 1', '3CPR/Controlled Shipping Level 2/3'],
    'Unauthorized Change': ['Unauthorized Change - Mass Production'],
    'Program Management': ['Minor', 'Major', 'Critical'],
    'SQD Escalation': ['Warning','Escalation Level 1', 'Escalation Level 2','Group NBH'],
    'Preventive In Field Action': ['Minor', 'Major', 'Critical'],
    'Cost Recovery': ['SQD Escalation Level 2']
}

export let currencyList = ['USA', 'CAN', 'MEX', 'EURO'];

export let incidentCategoryList = [
    "Customer Impact",
    "Customer Containment",
    "Unauthorized Change",
    "Program Management",
    "SQD Escalation",
    "Preventive In Field Action",
    "Cost Recovery"
]

export let technicalArea = [
    'Body Exterior', 
    'Interior', 
    'E-Propulsion Powertrain Systems',
    'EE & Modules', 
    'ICE Powertrain', 
    'Maserati',
    'Chassis & Adaptation'
]